name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      # The following steps only run when a new release is created
      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v7

      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install pnpm
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/action-setup@v5
        with:
          version: 8

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm install

      - name: Build Project
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm run build

      - name: Upload Release Asset
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} dist/armadarr-card.js#armadarr-card.js
